### PR TITLE
Implement testing frameworks, automated by grunt workflow. Include general folder structure and dummy files to match grunt configuration.

### PR DESCRIPTION
**Pull request by rjatkinson2**
- Implement testing frameworks, automated by grunt workflow. Include general folder structure and dummy files to match grunt configuration.
- Based on those changes, needed to cleanup a few files after linting to ensure grunt workflow is setup correctly.

### CODE REVIEW

**Comment by ajkitson** [comment]
Hey Ryan--could you do a PR that just includes the files needed for the testing config? That is, without the empty files or files that just have jshint changes. Merging this PR as is will introduce files to the repo that we're not using (e.g. ribbit.js) and will require people to rebase just to get some semi-colons (pretty sure SungMin's been doing a lot with server.js).

**Comment by rjatkinson2** [comment]
Sure. I only made these changes so the tests would be functional as we discussed but your concerns makes sense. I'll make the new request soon.

**Comment by rjatkinson2** [comment]
Updates have been made according to your request!

**Comment by ajkitson** [comment]
The changes look good, but I can't merge the PR in Github--you probably need to rebase if you haven't done so recently. 
screen shot 2015-03-21 at 2 10 29 pm

**Comment by rjatkinson2** [comment]
I have a good feeling about this one. My best attempt yet at getting it merged.

**Pull request merged**
